#!/usr/bin/env python3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
import argparse
from pathlib import Path

from nozlo.nozlo import Nozlo
from nozlo import __version__


LOG = logging.getLogger("nozlo")



def main():
    parser = argparse.ArgumentParser(
        description="""G-code viewer.""")

    parser.add_argument(
        "--verbose", "-v",
        action="count", default=0,
        help="Print verbose information for debugging.")
    parser.add_argument(
        "--quiet", "-q",
        action="count", default=0,
        help="Suppress warnings.")

    parser.add_argument(
        "--version", "-V",
        action="version",
        version=__version__)

    parser.add_argument(
        "gcode",
        metavar="GCODE",
        type=Path,
        help="Path to G-code file.")

    args = parser.parse_args()

    level = (logging.ERROR, logging.WARNING, logging.INFO, logging.DEBUG)[
        max(0, min(3, 1 + args.verbose - args.quiet))]
    handler = logging.StreamHandler()

    for name in ("nozlo", "parser"):
        log = logging.getLogger(name)
        log.addHandler(handler)
        log.setLevel(level)

    app = Nozlo()
    app.load_geo(args.gcode)
    app.run()



if __name__ == "__main__":
    main()
